name: Release Package

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
  
    - name: Build project
      run: dotnet build src\Umbraco.Community.CustomValueConverter.csproj --configuration Release

    - name: Push to NuGet
      run: dotnet nuget push **\*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

    - name: Push to GitHub
      run: dotnet nuget push **\*.nupkg  --api-key ${{secrets.LK_GITHUB_PAT}} --source https://nuget.pkg.github.com/leekelleher/index.json
